using System;
using System.ComponentModel.DataAnnotations;
using Domain.Entities.Common;
using Domain.Entities.Subscriptions;
using Domain.Enums;

namespace Domain.Entities.OnlineAccess;

/// <summary>
/// Represents a device registered for online access.
/// Unlike offline device bindings (hardware fingerprint validation),
/// online device bindings are API-based and more flexible.
/// </summary>
public class OnlineDeviceBinding : AuditEntity<Guid>
{
    /// <summary>
    /// The online token this device is bound to.
    /// </summary>
    public Guid TokenId { get; set; }
    
    /// <summary>
    /// The subscription this device is registered for.
    /// </summary>
    public Guid SubscriptionId { get; set; }
    
    /// <summary>
    /// Unique device fingerprint (generated by client app).
    /// </summary>
    [Required]
    [StringLength(256)]
    public required string DeviceFingerprint { get; set; }
    
    /// <summary>
    /// Friendly name for the device (e.g., "John's Laptop").
    /// </summary>
    [StringLength(100)]
    public string? DeviceName { get; set; }
    
    /// <summary>
    /// Device type (Desktop, Server, Mobile, VM, etc.).
    /// </summary>
    [StringLength(50)]
    public string? DeviceType { get; set; }
    
    /// <summary>
    /// Operating system info.
    /// </summary>
    [StringLength(100)]
    public string? OperatingSystem { get; set; }
    
    /// <summary>
    /// Current status of the device binding.
    /// </summary>
    public OnlineDeviceStatus Status { get; set; } = OnlineDeviceStatus.Active;
    
    /// <summary>
    /// When the device was first registered.
    /// </summary>
    public DateTime FirstSeenAtUtc { get; set; } = DateTime.UtcNow;
    
    /// <summary>
    /// When the device was last seen (last API call).
    /// </summary>
    public DateTime? LastSeenAtUtc { get; set; }
    
    /// <summary>
    /// Last known IP address of the device.
    /// </summary>
    [StringLength(45)]
    public string? LastIpAddress { get; set; }
    
    /// <summary>
    /// Last known user agent of the device.
    /// </summary>
    [StringLength(500)]
    public string? LastUserAgent { get; set; }
    
    /// <summary>
    /// Number of API calls made from this device.
    /// </summary>
    public long ApiCallCount { get; set; } = 0;
    
    /// <summary>
    /// Optional reason if device was suspended/revoked.
    /// </summary>
    [StringLength(500)]
    public string? StatusReason { get; set; }
    
    // ========== Navigation Properties ==========
    
    public virtual OnlineClientToken Token { get; set; } = null!;
    public virtual Subscription Subscription { get; set; } = null!;
}
